-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME from ANIMAL_INS
WHERE INTAKE_CONDITION != "Aged"
ORDER BY ANIMAL_ID


-- 코드를 입력하세요
# SELECT ANIMAL_ID, NAME from ANIMAL_INS
# WHERE INTAKE_CONDITION = 'SICK'
# ORDER BY ANIMAL_ID